library(tidyverse)

abcd_smri_colnames <- "FS_InterCranial_Vol = smri_vol_scs_intracranialv, #technically inter vs intra
#FS_BrainSeg_Vol
#FS_BrainSeg_Vol_No_Vent
#FS_BrainSeg_Vol_No_Vent_Surf
FS_LCort_GM_Vol = smri_vol_cdk_totallh,
FS_RCort_GM_Vol = smri_vol_cdk_totalrh,
FS_TotCort_GM_Vol = smri_vol_cdk_total, #total whole brain cortical volume
FS_SubCort_GM_Vol = smri_vol_scs_subcorticalgv,
#FS_Total_GM_Vol #maybe just calculate?
FS_SupraTentorial_Vol = smri_vol_scs_suprateialv, #assuming this includes all ventricles
#FS_SupraTentorial_Vol_No_Vent  #smri_vol_scs_allventricles is all ventricles, subtract?
#FS_SupraTentorial_No_Vent_Voxel_Count
#FS_Mask_Vol
#FS_BrainSegVol_eTIV_Ratio
#FS_MaskVol_eTIV_Ratio
FS_L_LatVent_Vol = smri_vol_scs_ltventriclelh,
FS_L_InfLatVent_Vol = smri_vol_scs_inflatventlh,
FS_L_Cerebellum_WM_Vol = smri_vol_scs_crbwmatterlh,
FS_L_Cerebellum_Cort_Vol = smri_vol_scs_crbcortexlh,
FS_L_ThalamusProper_Vol = smri_vol_scs_tplh,
FS_L_Caudate_Vol = smri_vol_scs_caudatelh,
FS_L_Putamen_Vol = smri_vol_scs_putamenlh,
FS_L_Pallidum_Vol = smri_vol_scs_pallidumlh,
FS_3rdVent_Vol = smri_vol_scs_3rdventricle,
FS_4thVent_Vol = smri_vol_scs_4thventricle,
FS_BrainStem_Vol = smri_vol_scs_bstem,
FS_L_Hippo_Vol = smri_vol_scs_hpuslh,
FS_L_Amygdala_Vol =	smri_vol_scs_amygdalalh,
FS_CSF_Vol = smri_vol_scs_csf,
FS_L_AccumbensArea_Vol = smri_vol_scs_aal,
FS_L_VentDC_Vol = smri_vol_scs_vedclh,
#FS_L_Vessel_Vol
#FS_L_ChoroidPlexus_Vol
FS_R_LatVent_Vol = 	smri_vol_scs_ltventriclerh,
FS_R_InfLatVent_Vol = smri_vol_scs_inflatventrh,
FS_R_Cerebellum_WM_Vol = smri_vol_scs_crbwmatterrh,
FS_R_Cerebellum_Cort_Vol = smri_vol_scs_crbcortexrh,
FS_R_ThalamusProper_Vol = smri_vol_scs_tprh,
FS_R_Caudate_Vol = smri_vol_scs_caudaterh,
FS_R_Putamen_Vol = smri_vol_scs_putamenrh,
FS_R_Pallidum_Vol = smri_vol_scs_pallidumrh,
FS_R_Hippo_Vol = smri_vol_scs_hpusrh,
FS_R_Amygdala_Vol = smri_vol_scs_amygdalarh,
FS_R_AccumbensArea_Vol = 	smri_vol_scs_aar,
FS_R_VentDC_Vol = smri_vol_scs_vedcrh,
#FS_R_Vessel_Vol
#FS_R_ChoroidPlexus_Vol
#FS_OpticChiasm_Vol
FS_CC_Posterior_Vol = smri_vol_scs_ccps,
FS_CC_MidPosterior_Vol = smri_vol_scs_ccmidps,
FS_CC_Central_Vol = smri_vol_scs_ccct,
FS_CC_MidAnterior_Vol = smri_vol_scs_ccmidat,
FS_CC_Anterior_Vol = smri_vol_scs_ccat,
FS_L_Bankssts_Area = 	smri_area_cdk_banksstslh,
FS_L_Caudalanteriorcingulate_Area = smri_area_cdk_cdacatelh,
FS_L_Caudalmiddlefrontal_Area = smri_area_cdk_cdmdfrlh,
FS_L_Cuneus_Area = 	smri_area_cdk_cuneuslh,
FS_L_Entorhinal_Area = smri_area_cdk_ehinallh,
FS_L_Fusiform_Area = smri_area_cdk_fusiformlh,
FS_L_Inferiorparietal_Area = smri_area_cdk_ifpllh,
FS_L_Inferiortemporal_Area = smri_area_cdk_iftmlh,
FS_L_Isthmuscingulate_Area = smri_area_cdk_ihcatelh,
FS_L_Lateraloccipital_Area = smri_area_cdk_locclh,
FS_L_Lateralorbitofrontal_Area = smri_area_cdk_lobfrlh,
FS_L_Lingual_Area = smri_area_cdk_linguallh,
FS_L_Medialorbitofrontal_Area = smri_area_cdk_mobfrlh,
FS_L_Middletemporal_Area = smri_area_cdk_mdtmlh,
FS_L_Parahippocampal_Area = smri_area_cdk_parahpallh,
FS_L_Paracentral_Area = smri_area_cdk_paracnlh,
FS_L_Parsopercularis_Area = smri_area_cdk_parsopclh,
FS_L_Parsorbitalis_Area = smri_area_cdk_parsobislh,
FS_L_Parstriangularis_Area = smri_area_cdk_parstgrislh,
FS_L_Pericalcarine_Area = smri_area_cdk_pericclh,
FS_L_Postcentral_Area = smri_area_cdk_postcnlh,
FS_L_Posteriorcingulate_Area = smri_area_cdk_ptcatelh,
FS_L_Precentral_Area = smri_area_cdk_precnlh,
FS_L_Precuneus_Area = smri_area_cdk_pclh,
FS_L_Rostralanteriorcingulate_Area = smri_area_cdk_rracatelh,
FS_L_Rostralmiddlefrontal_Area = smri_area_cdk_rrmdfrlh,
FS_L_Superiorfrontal_Area = smri_area_cdk_sufrlh,
FS_L_Superiorparietal_Area = smri_area_cdk_supllh,
FS_L_Superiortemporal_Area = smri_area_cdk_sutmlh,
FS_L_Supramarginal_Area = smri_area_cdk_smlh,
FS_L_Frontalpole_Area = smri_area_cdk_frpolelh,
FS_L_Temporalpole_Area = smri_area_cdk_tmpolelh,
FS_L_Transversetemporal_Area = smri_area_cdk_trvtmlh,
FS_L_Insula_Area = smri_area_cdk_insulalh,
FS_R_Bankssts_Area = smri_area_cdk_banksstsrh,
FS_R_Caudalanteriorcingulate_Area = smri_area_cdk_cdacaterh,
FS_R_Caudalmiddlefrontal_Area = smri_area_cdk_cdmdfrrh,
FS_R_Cuneus_Area = smri_area_cdk_cuneusrh,
FS_R_Entorhinal_Area = smri_area_cdk_ehinalrh,
FS_R_Fusiform_Area = smri_area_cdk_fusiformrh,
FS_R_Inferiorparietal_Area = smri_area_cdk_ifplrh,
FS_R_Inferiortemporal_Area = 	smri_area_cdk_iftmrh,
FS_R_Isthmuscingulate_Area = smri_area_cdk_ihcaterh,
FS_R_Lateraloccipital_Area = smri_area_cdk_loccrh,
FS_R_Lateralorbitofrontal_Area = smri_area_cdk_lobfrrh,
FS_R_Lingual_Area = smri_area_cdk_lingualrh,
FS_R_Medialorbitofrontal_Area = smri_area_cdk_mobfrrh,
FS_R_Middletemporal_Area = smri_area_cdk_mdtmrh,
FS_R_Parahippocampal_Area = smri_area_cdk_parahpalrh,
FS_R_Paracentral_Area = smri_area_cdk_paracnrh,
FS_R_Parsopercularis_Area = smri_area_cdk_parsopcrh,
FS_R_Parsorbitalis_Area = smri_area_cdk_parsobisrh,
FS_R_Parstriangularis_Area = smri_area_cdk_parstgrisrh,
FS_R_Pericalcarine_Area = smri_area_cdk_periccrh,
FS_R_Postcentral_Area = smri_area_cdk_postcnrh,
FS_R_Posteriorcingulate_Area = smri_area_cdk_ptcaterh,
FS_R_Precentral_Area = smri_area_cdk_precnrh,
FS_R_Precuneus_Area = smri_area_cdk_pcrh,
FS_R_Rostralanteriorcingulate_Area = smri_area_cdk_rracaterh,
FS_R_Rostralmiddlefrontal_Area = smri_area_cdk_rrmdfrrh,
FS_R_Superiorfrontal_Area = smri_area_cdk_sufrrh,
FS_R_Superiorparietal_Area = 	smri_area_cdk_suplrh,
FS_R_Superiortemporal_Area = smri_area_cdk_sutmrh,
FS_R_Supramarginal_Area = smri_area_cdk_smrh,
FS_R_Frontalpole_Area = smri_area_cdk_frpolerh,
FS_R_Temporalpole_Area = smri_area_cdk_tmpolerh,
FS_R_Transversetemporal_Area = smri_area_cdk_trvtmrh,
FS_R_Insula_Area = smri_area_cdk_insularh,
#abcd technically doesn't say gray matter volume for the following varibles
FS_L_Bankssts_GrayVol = smri_vol_cdk_banksstslh,
FS_L_Caudalanteriorcingulate_GrayVol = smri_vol_cdk_cdacatelh,
FS_L_Caudalmiddlefrontal_GrayVol = smri_vol_cdk_cdmdfrlh,
FS_L_Cuneus_GrayVol = smri_vol_cdk_cuneuslh,
FS_L_Entorhinal_GrayVol = smri_vol_cdk_ehinallh,
FS_L_Fusiform_GrayVol = smri_vol_cdk_fusiformlh,
FS_L_Inferiorparietal_GrayVol = smri_vol_cdk_ifpllh,
FS_L_Inferiortemporal_GrayVol = smri_vol_cdk_iftmlh,
FS_L_Isthmuscingulate_GrayVol = smri_vol_cdk_ihcatelh,
FS_L_Lateraloccipital_GrayVol = smri_vol_cdk_locclh,
FS_L_Lateralorbitofrontal_GrayVol = smri_vol_cdk_lobfrlh,
FS_L_Lingual_GrayVol = smri_vol_cdk_linguallh,
FS_L_Medialorbitofrontal_GrayVol = smri_vol_cdk_mobfrlh,
FS_L_Middletemporal_GrayVol = smri_vol_cdk_mdtmlh,
FS_L_Parahippocampal_GrayVol = smri_vol_cdk_parahpallh,
FS_L_Paracentral_GrayVol = smri_vol_cdk_paracnlh,
FS_L_Parsopercularis_GrayVol = smri_vol_cdk_parsopclh,
FS_L_Parsorbitalis_GrayVol = smri_vol_cdk_parsobislh,
FS_L_Parstriangularis_GrayVol = smri_vol_cdk_parstgrislh,
FS_L_Pericalcarine_GrayVol = smri_vol_cdk_pericclh,
FS_L_Postcentral_GrayVol = smri_vol_cdk_postcnlh,
FS_L_Posteriorcingulate_GrayVol = smri_vol_cdk_ptcatelh,
FS_L_Precentral_GrayVol = smri_vol_cdk_precnlh,
FS_L_Precuneus_GrayVol = smri_vol_cdk_pclh,
FS_L_Rostralanteriorcingulate_GrayVol = smri_vol_cdk_rracatelh,
FS_L_Rostralmiddlefrontal_GrayVol = smri_vol_cdk_rrmdfrlh,
FS_L_Superiorfrontal_GrayVol = smri_vol_cdk_sufrlh,
FS_L_Superiorparietal_GrayVol = smri_vol_cdk_supllh,
FS_L_Superiortemporal_GrayVol = smri_vol_cdk_sutmlh,
FS_L_Supramarginal_GrayVol = smri_vol_cdk_smlh,
FS_L_Frontalpole_GrayVol = smri_vol_cdk_frpolelh,
FS_L_Temporalpole_GrayVol = smri_vol_cdk_tmpolelh,
FS_L_Transversetemporal_GrayVol = smri_vol_cdk_trvtmlh,
FS_L_Insula_GrayVol = smri_vol_cdk_insulalh,
FS_R_Bankssts_GrayVol = smri_vol_cdk_banksstsrh,
FS_R_Caudalanteriorcingulate_GrayVol = smri_vol_cdk_cdacaterh,
FS_R_Caudalmiddlefrontal_GrayVol = 	smri_vol_cdk_cdmdfrrh,
FS_R_Cuneus_GrayVol = smri_vol_cdk_cuneusrh,
FS_R_Entorhinal_GrayVol = smri_vol_cdk_ehinalrh,
FS_R_Fusiform_GrayVol = smri_vol_cdk_fusiformrh,
FS_R_Inferiorparietal_GrayVol = smri_vol_cdk_ifplrh,
FS_R_Inferiortemporal_GrayVol = smri_vol_cdk_iftmrh,
FS_R_Isthmuscingulate_GrayVol = smri_vol_cdk_ihcaterh,
FS_R_Lateraloccipital_GrayVol = smri_vol_cdk_loccrh,
FS_R_Lateralorbitofrontal_GrayVol = smri_vol_cdk_lobfrrh,
FS_R_Lingual_GrayVol = smri_vol_cdk_lingualrh,
FS_R_Medialorbitofrontal_GrayVol = smri_vol_cdk_mobfrrh,
FS_R_Middletemporal_GrayVol = smri_vol_cdk_mdtmrh,
FS_R_Parahippocampal_GrayVol = smri_vol_cdk_parahpalrh,
FS_R_Paracentral_GrayVol = smri_vol_cdk_paracnrh,
FS_R_Parsopercularis_GrayVol = smri_vol_cdk_parsopcrh,
FS_R_Parsorbitalis_GrayVol = smri_vol_cdk_parsobisrh,
FS_R_Parstriangularis_GrayVol = smri_vol_cdk_parstgrisrh,
FS_R_Pericalcarine_GrayVol = smri_vol_cdk_periccrh,
FS_R_Postcentral_GrayVol = smri_vol_cdk_postcnrh,
FS_R_Posteriorcingulate_GrayVol = 	smri_vol_cdk_ptcaterh,
FS_R_Precentral_GrayVol = smri_vol_cdk_precnrh,
FS_R_Precuneus_GrayVol = smri_vol_cdk_pcrh,
FS_R_Rostralanteriorcingulate_GrayVol = smri_vol_cdk_rracaterh,
FS_R_Rostralmiddlefrontal_GrayVol = smri_vol_cdk_rrmdfrrh,
FS_R_Superiorfrontal_GrayVol = smri_vol_cdk_sufrrh,
FS_R_Superiorparietal_GrayVol = smri_vol_cdk_suplrh,
FS_R_Superiortemporal_GrayVol = smri_vol_cdk_sutmrh,
FS_R_Supramarginal_GrayVol = smri_vol_cdk_smrh,
FS_R_Frontalpole_GrayVol = smri_vol_cdk_frpolerh,
FS_R_Temporalpole_GrayVol = smri_vol_cdk_tmpolerh,
FS_R_Transversetemporal_GrayVol = smri_vol_cdk_trvtmrh,
FS_R_Insula_GrayVol = smri_vol_cdk_insularh" %>% 
  str_split("\n") %>% 
  unlist() %>% 
  .[!startsWith(., "#")] %>% 
  map_chr(~str_split(., "=") %>% 
            unlist() %>% 
            pluck(2) %>% 
            str_split(., ",") %>% 
            unlist() %>% 
            pluck(1) %>% 
            str_trim(side = "left"))

write_rds(abcd_smri_colnames, file = here::here("data", "abcd_smri_colnames.rds"))
write_lines(abcd_smri_colnames, file = here::here("data", "abcd_smri_colnames.txt"))
